USE [master]
GO
/****** Object:  Database [MCashMTB]    Script Date: 10/26/2017 7:19:56 PM ******/
CREATE DATABASE [MCashMTB]
 GO
ALTER DATABASE [MCashMTB] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MCashMTB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MCashMTB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MCashMTB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MCashMTB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MCashMTB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MCashMTB] SET ARITHABORT OFF 
GO
ALTER DATABASE [MCashMTB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MCashMTB] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [MCashMTB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MCashMTB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MCashMTB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MCashMTB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MCashMTB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MCashMTB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MCashMTB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MCashMTB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MCashMTB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MCashMTB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MCashMTB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MCashMTB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MCashMTB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MCashMTB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MCashMTB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MCashMTB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MCashMTB] SET RECOVERY FULL 
GO
ALTER DATABASE [MCashMTB] SET  MULTI_USER 
GO
ALTER DATABASE [MCashMTB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MCashMTB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MCashMTB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MCashMTB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [MCashMTB]
GO
/****** Object:  Table [dbo].[BankAccount]    Script Date: 10/26/2017 7:19:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BankAccount](
	[AccountNumber] [varchar](100) NOT NULL,
	[AccountHolder] [varchar](200) NULL,
	[AccountCurrency] [varchar](200) NULL,
	[OpeningBalance] [numeric](18, 2) NULL,
	[ClosingBalance] [numeric](18, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[AccountNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TransactionDetails]    Script Date: 10/26/2017 7:19:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TransactionDetails](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[AccountNumber] [varchar](100) NOT NULL,
	[TransactionDate] [datetime] NULL,
	[Reference] [varchar](100) NULL,
	[Description] [varchar](500) NULL,
	[Debit] [decimal](18, 2) NULL,
	[Credit] [decimal](18, 2) NULL,
	[Balance] [decimal](18, 2) NULL,
 CONSTRAINT [PK_TransactionDetails] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
USE [master]
GO
ALTER DATABASE [MCashMTB] SET  READ_WRITE 
GO
Use [MCashMTB]

INSERT INTO [dbo].[BankAccount]
           ([AccountNumber]
           ,[AccountHolder]
           ,[AccountCurrency]
           ,[OpeningBalance]
           ,[ClosingBalance])
     VALUES
           ('1061260210000'
           ,'Shafqat Ahmed'
           ,'BDT'
           ,40000
           ,40000
		   )
